version: '3.7'
services:
  app:
    build:
      context: .
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - "5174:5174" # remix dev server
      - "4173:4173" # vite preview server
      - "8808:8808" # gin server
    volumes:
      - ./:/app
      - ~/.bashrc:/root/.bashrc
  mysql:
    platform: linux/x86_64
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
