version: '3.7'
services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - "5174:5174" # remix dev server
      - "4173:4173" # vite preview server
      - "8808:8808" # gin server
