openapi: '3.0.0'
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    $ref: './paths/pets.yml'
  /pets/{petId}:
    $ref: './paths/pets/pet.yml'
